# **Import Libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print("Libraies Loaded Boss✅")

Libraies Loaded Boss✅

# **Data Exploration**

## *Load The Data*

In [2]:
File_path = input("Enter The File Path: ").replace('\\','\\')

df = pd.read_csv(File_path)
print('Data Loaded Successfully✅')

Data Loaded Successfully✅

## *Data Exploration*

In [ ]:
# Data have 50k entry with 24 coloums
df.shape

(50000, 24)

In [5]:
# Transpose the data for better reading
df.head(10).T

,0,1,2,3,4,5,6,7,8,9
transaction_id,4784,28779,37597,44058,49115,10408,2620,3378,13924,29946
customer_id,CUST8189,CUST6564,CUST2413,CUST8973,CUST4060,CUST4547,CUST2407,CUST5476,CUST5131,CUST1117
customer_name,SIMRAN DAS,Nikhil Reddy,Shreya Chopra,Arjun Joshi,Pooja Joshi,Siddharth Das,Priya Das,Zara Chopra,sneha singh,Riya Iyer
age,NaN,13,NaN,27,150,25,150,17,23,24
age_group,Young Adult (18-24),Young Adult (18-24),NaN,Young Adult (18-24),Young Adult (18-24),Young Adult (18-24),Young Adult (18-24),Young Adult (18-24),Adult (25-30),Young Adult (18-24)
city,Kolkata,Mumbai,Pune,Chennai,Bangalore,Mumbai,Hyderabad,Lucknow,Jaipur,Bangalore
email,simran.das@gmail.com,NaN,shreya.chopra@gmail.com,NaN,pooja.joshi@gmail.com,siddharth.das@gmail.com,priya.das@@gmail.com,zara.chopra@gmail.com,sneha.singh@gmail.com,NaN
phone,NaN,9025371511,9779267699,9966018593,971833,9685329623,9066815814,9903006244,99582-83857,9838348029
manga_title,DR. STONE,One Punch Man,DEMON SLAYER,Death Note,The Promised Neverland,One Punch Man,One Punch Man,Black Clover,Mob Psycho 100,Chainsaw Man
volume_no,23.0,3.0,17.0,14.0,16.0,35.0,38.0,1.0,10.0,2.0
genre,Thriller,Shonen,Fantasy,ACTION,Seinen,Shonen,Slice of Life,ACTION,Horror,Shonen
format,Paperback,Box Set,Box Set,Digital,Hardcover,Paperback,Digital,Hardcover,Box Set,Digital
platform,Amazon,Amazon,MangaPlus Shop,-,Flipkart,Amazon,Book Depository,Crunchyroll Store,Crunchyroll Store,MangaPlus Shop
payment_method,NaN,NaN,Cash,Cash,Debit Card,UPI,Net Banking,Debit Card,UPI,UPI
unit_price,349,299.00,Rs.1299,799,349,1499/-,199,199,349,499
quantity,1.0,4.0,1.0,2.0,5.0,NaN,3.0,1.0,3.0,5.0
total_amount,349,1196,1299,1598,1745,NaN,597,199,1047,NaN
customer_rating,4.4,2.5,4.1,4.9,4.7,4.2,3.6,3.0,NaN,2.7
purchase_date,06/08/22,19 February 2020,2021/07/06,27 September 2021,11/24/24,03-03-2022,August 2022,2022-05-12T00:00:00Z,15-01-2024,18 August 2020
delivery_days,12.0,8.0,7.0,6.0,4.0,11.0,-1.0,1.0,NaN,1.0
is_returned,False,1,True,yes,no,No,no,NaN,No,False
membership_tier,Bronze,NaN,NaN,Silver,NaN,Bronze,Platinum,NaN,Gold,Bronze
discount_percent,25,0,0,20,5,15,NaN,20,0,20
coupon_used,No,Yes,none,Yes,NaN,Yes,-,Yes,none,No

In [7]:
df.tail(10).T

,49990,49991,49992,49993,49994,49995,49996,49997,49998,49999
transaction_id,13278,6571,37752,5877,40272,11641,19165,35949,42242,7566
customer_id,CUST7482,CUST7829,CUST4657,CUST8558,CUST1143,CUST9704,CUST8459,CUST4192,CUST1189,CUST8347
customer_name,Divya Patel,Harsh Joshi,Shreya Shah,Karan Malhotra,Harsh Shah,Pooja Verma,Vikram Das,Amit Gupta,AMIT SINGH,Nikhil Reddy
age,30,27,-27,18,20,24,17,30,28,30
age_group,Young Adult (18-24),Young Adult (18-24),Adult (25-30),Young Adult (18-24),Teen (13-17),Adult (25-30),Teen (13-17),Adult (25-30),Adult (25-30),Young Adult (18-24)
city,Kolkata,Pune,Kolkata,Bangalore,Ahmedabad,Lucknow,Mumbai,Mumbai,Delhi,Pune
email,divya.patel@gmail.com,harsh.joshi@gmail.com,shreya.shah@gmail.com,karan.malhotra@gmail.com,harsh.shah@gmail.com,pooja.vermagmail.com,vikram.das@gmail.com,amit.gupta@gmail.com,amit.singh@gmail,nikhil.reddy@gmail.com
phone,92811-73105,9727005035,9005758089,NaN,9876829355,NaN,9709716982,9678982355,9831289524,9605167734
manga_title,Spy x Family,Dr. Stone,Attack on Titan,One Piece,Naruto,Fairy Tail,Fullmetal Alchemist,Vinland Saga,Fairy Tail,BLEACH
volume_no,NaN,21.0,-37.0,NaN,36.0,34.0,13.0,9.0,13.0,NaN
genre,Slice of Life,Isekai,Fantasy,Shonen,Fantasy,Slice of Life,Shojo,Romance,Thriller,ROMANCE
format,Limited Edition,Paperback,Limited Edition,NaN,Limited Edition,Digital,Hardcover,Digital,Hardcover,Box Set
platform,Crunchyroll Store,Local Store,Flipkart,Flipkart,Crunchyroll Store,Flipkart,Book Depository,Book Depository,MangaPlus Shop,Amazon
payment_method,Net Banking,Debit Card,UPI,Debit Card,Credit Card,Cash,UPI,Wallet,Credit Card,Cash
unit_price,599,299,599,NaN,199,349,599,349,1299,349
quantity,4.0,3.0,3.0,2.0,4.0,1.0,5.0,4.0,NaN,1.0
total_amount,999999,897/-,1797,998,796,349,2995,NaN,5196,349
customer_rating,2.8,3.1,4.0,7.360084,3.6,4.9,4.1,2.7,-1.0,3.2
purchase_date,June 2024,19.03.2023,2023/05/22,2020/11/19,11.12.2021,20-08-2023,December 2022,22-12-2020,October 2024,24.08.2020
delivery_days,3.0,12.0,5.0,10.0,11.0,3.0,2.0,3.0,-3.0,9.0
is_returned,0,yes,yes,no,NO,True,NaN,0,No,No
membership_tier,bronze,SILVER,Gold,Gold,UNKNOWN,Platinum,Gold,Silver,Gold,Platinum
discount_percent,0,20,25,NaN,5,5,5,5,10,20
coupon_used,Unknown,NaN,NaN,Unknown,none,NaN,none,Yes,NaN,No

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    50000 non-null  int64
 1   customer_id       49007 non-null  str
 2   customer_name     50000 non-null  str
 3   age               47504 non-null  str
 4   age_group         47992 non-null  str
 5   city              50000 non-null  str
 6   email             46987 non-null  str
 7   phone             47508 non-null  str
 8   manga_title       50000 non-null  str
 9   volume_no         47557 non-null  float64
 10  genre             50000 non-null  str
 11  format            48068 non-null  str
 12  platform          48018 non-null  str
 13  payment_method    48030 non-null  str
 14  unit_price        47472 non-null  str
 15  quantity          47417 non-null  float64
 16  total_amount      47396 non-null  str
 17  customer_rating   45933 non-null  float64
 18  purchase_date     45050 non-null  str
 19  delivery_days     47483 non-null  float64
 20  is_returned       47921 non-null  str
 21  membership_tier   41437 non-null  str
 22  discount_percent  48055 non-null  str
 23  coupon_used       29723 non-null  str
dtypes: float64(4), int64(1), str(19)
memory usage: 9.2 MB

In [ ]:
#Drop the 50%> NaN values col (Optional)
print('NaN Value % in col: ')
print(round((df.isna().sum()/df.count())*100,2))

NaN Value % in col:
transaction_id       0.00
customer_id          2.03
customer_name        0.00
age                  5.25
age_group            4.18
city                 0.00
email                6.41
phone                5.25
manga_title          0.00
volume_no            5.14
genre                0.00
format               4.02
platform             4.13
payment_method       4.10
unit_price           5.33
quantity             5.45
total_amount         5.49
customer_rating      8.85
purchase_date       10.99
delivery_days        5.30
is_returned          4.34
membership_tier     20.67
discount_percent     4.05
coupon_used         68.22
dtype: float64

In [14]:
print("Duplicates in the Data is",df.duplicated().sum())

Duplicates in the Data is 943

# **Data Cleaning**

In [107]:
df_copy = df.copy()
print('Copy created')

Copy created

## *Data Type Collrection*

In [108]:
# Customer name column
replacements = {'@':'a','3':'e','0':'o'}

df_copy['customer_name'] = (
    df_copy['customer_name']
    .replace(replacements, regex=True)
    .str.strip()
    .str.title()
)

# Age Column
replacements = {'years':'','unknown':np.nan}
for char, replacement in replacements.items():
    df_copy['age'] = df_copy['age'].replace(char,replacement,regex=True).str.strip()
df_copy['age'] = df_copy['age'].astype('float')

#Age group
unknown = df_copy['age_group'].unique().tolist()

valid = ['Young Adult (18-24)','Adult (25-30)','Teen (13-17)']

to_replace = {item: 'Unknown' for item in unknown if item not in valid}

df_copy['age_group'] = df_copy['age_group'].replace(to_replace)

df_copy = df_copy[df_copy['age_group'] != '-']

In [54]:
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    50000 non-null  int64
 1   customer_id       49007 non-null  str
 2   customer_name     50000 non-null  str
 3   age               46471 non-null  float64
 4   age_group         47992 non-null  str
 5   city              50000 non-null  str
 6   email             46987 non-null  str
 7   phone             47508 non-null  str
 8   manga_title       50000 non-null  str
 9   volume_no         47557 non-null  float64
 10  genre             50000 non-null  str
 11  format            48068 non-null  str
 12  platform          48018 non-null  str
 13  payment_method    48030 non-null  str
 14  unit_price        47472 non-null  str
 15  quantity          47417 non-null  float64
 16  total_amount      47396 non-null  str
 17  customer_rating   45933 non-null  float64
 18  purchase_date     45050 non-null  str
 19  delivery_days     47483 non-null  float64
 20  is_returned       47921 non-null  str
 21  membership_tier   41437 non-null  str
 22  discount_percent  48055 non-null  str
 23  coupon_used       29723 non-null  str
dtypes: float64(5), int64(1), str(18)
memory usage: 9.2 MB

In [109]:
df_copy.head(20).T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
transaction_id,4784,28779,37597,44058,49115,10408,2620,3378,13924,29946,7019,49769,37817,8855,39383,4112,4373,25759,43584,48701
customer_id,CUST8189,CUST6564,CUST2413,CUST8973,CUST4060,CUST4547,CUST2407,CUST5476,CUST5131,CUST1117,CUST6777,CUST6096,CUST5172,CUST9205,CUST8577,CUST6737,CUST4634,CUST2485,CUST9452,CUST6753
customer_name,Simran Das,Nikhil Reddy,Shreya Chopra,Arjun Joshi,Pooja Joshi,Siddharth Das,Priya Das,Zara Chopra,Sneha Singh,Riya Iyer,Priya Sharma,Rohan Verma,Simran Kumar,Sneha Shah,Harsh Verma,Kavya Singh,Meera Nair,Aditya Iyer,Priya Gupta,Sneha Malhotra
age,NaN,13.0,NaN,27.0,150.0,25.0,150.0,17.0,23.0,24.0,23.0,24.0,14.0,22.0,16.0,17.0,30.0,23.0,14.0,18.0
age_group,Young Adult (18-24),Young Adult (18-24),Unknown,Young Adult (18-24),Young Adult (18-24),Young Adult (18-24),Young Adult (18-24),Young Adult (18-24),Adult (25-30),Young Adult (18-24),Unknown,Unknown,Young Adult (18-24),Adult (25-30),Teen (13-17),Adult (25-30),Teen (13-17),Young Adult (18-24),Adult (25-30),Adult (25-30)
city,Kolkata,Mumbai,Pune,Chennai,Bangalore,Mumbai,Hyderabad,Lucknow,Jaipur,Bangalore,Jaipur,Lucknow,Bangalore,PUNE,Chennai,Lucknow,Hyderabad,Lucknow,Delhi,Ahmedabad
email,simran.das@gmail.com,NaN,shreya.chopra@gmail.com,NaN,pooja.joshi@gmail.com,siddharth.das@gmail.com,priya.das@@gmail.com,zara.chopra@gmail.com,sneha.singh@gmail.com,NaN,priya.sharma@gmail.com,rohan.verma@gmail.com,simran.kumar@gmail.com,sneha.shah@gmail.com,harsh.verma@gmail.com,kavya.singh@gmail,meera.nairgmail.com,aditya.iyer@gmail.com,priya.gupta@@gmail.com,sneha.malhotragmail.com
phone,NaN,9025371511,9779267699,9966018593,971833,9685329623,9066815814,9903006244,99582-83857,9838348029,9672393684,9460116884,9653138725,9049190476,91391-57380,966604,9061928889,9128174403,9351682668,9651835622
manga_title,DR. STONE,One Punch Man,DEMON SLAYER,Death Note,The Promised Neverland,One Punch Man,One Punch Man,Black Clover,Mob Psycho 100,Chainsaw Man,Hunter x Hunter,Attack on Titan,Attack on Titan,Sword Art Online,One Piece,Demon Slayer,One Punch Man,Mob Psycho 100,Death Note,One Piece
volume_no,23.0,3.0,17.0,14.0,16.0,35.0,38.0,1.0,10.0,2.0,29.0,22.0,12.0,39.0,36.0,20.0,6.0,13.0,35.0,1.0
genre,Thriller,Shonen,Fantasy,ACTION,Seinen,Shonen,Slice of Life,ACTION,Horror,Shonen,shojo,Slice of Life,Action,Fantasy,Thriller,Romance,Seinen,Fantasy,Shojo,thriller
format,Paperback,Box Set,Box Set,Digital,Hardcover,Paperback,Digital,Hardcover,Box Set,Digital,Paperback,Paperback,Box Set,Limited Edition,Hardcover,Limited Edition,Limited Edition,NaN,Hardcover,Box Set
platform,Amazon,Amazon,MangaPlus Shop,-,Flipkart,Amazon,Book Depository,Crunchyroll Store,Crunchyroll Store,MangaPlus Shop,Amazon,Flipkart,Viz Media,Viz Media,NaN,Viz Media,Viz Media,Book Depository,NaN,Crunchyroll Store
payment_method,NaN,NaN,Cash,Cash,Debit Card,UPI,Net Banking,Debit Card,UPI,UPI,NaN,Credit Card,UPI,Wallet,Net Banking,NaN,Credit Card,NaN,Credit Card,Debit Card
unit_price,349,299.00,Rs.1299,799,349,1499/-,199,199,349,499,199,799.00,₹ 199,199,199.00,199,799,199,999,349
quantity,1.0,4.0,1.0,2.0,5.0,NaN,3.0,1.0,3.0,5.0,3.0,1.0,2.0,3.0,9999.0,3.0,3.0,3.0,4.0,5.0
total_amount,349,1196,1299,1598,1745,NaN,597,199,1047,NaN,597,799,398/-,597,NaN,597,2397,₹ 597,₹ 3996,1745
customer_rating,4.4,2.5,4.1,4.9,4.7,4.2,3.6,3.0,NaN,2.7,3.9,3.1,9.175353,3.0,3.1,5.0,4.1,2.9,2.9,4.2
purchase_date,06/08/22,19 February 2020,2021/07/06,27 September 2021,11/24/24,03-03-2022,August 2022,2022-05-12T00:00:00Z,15-01-2024,18 August 2020,2022/10/21,August 2024,01 January 2024,04.06.2023,22.05.2023,08 December 2020,01/16/22,March 2021,18.06.2020,2022/01/09
delivery_days,12.0,8.0,7.0,6.0,4.0,11.0,-1.0,1.0,NaN,1.0,2.0,1.0,9.0,2.0,11.0,15.0,10.0,5.0,6.0,9999.0
is_returned,False,1,True,yes,no,No,no,NaN,No,False,Yes,1,-,1,0,No,True,False,True,False
membership_tier,Bronze,NaN,NaN,Silver,NaN,Bronze,Platinum,NaN,Gold,Bronze,Bronze,Bronze,Platinum,Silver,Gold,Silver,Platinum,Silver,Platinum,NaN
discount_percent,25,0,0,20,5,15,NaN,20,0,20,25,25,20,15,5,0,10,10,20,10
coupon_used,No,Yes,none,Yes,NaN,Yes,-,Yes,none,No,NaN,none,NaN,No,NaN,No,NaN,No,Yes,none

In [28]:
df.head(20).T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
transaction_id,4784,28779,37597,44058,49115,10408,2620,3378,13924,29946,7019,49769,37817,8855,39383,4112,4373,25759,43584,48701
customer_id,CUST8189,CUST6564,CUST2413,CUST8973,CUST4060,CUST4547,CUST2407,CUST5476,CUST5131,CUST1117,CUST6777,CUST6096,CUST5172,CUST9205,CUST8577,CUST6737,CUST4634,CUST2485,CUST9452,CUST6753
customer_name,SIMRAN DAS,Nikhil Reddy,Shreya Chopra,Arjun Joshi,Pooja Joshi,Siddharth Das,Priya Das,Zara Chopra,sneha singh,Riya Iyer,Priya Sharma,Rohan Verma,simran kumar,Sn3h@ Sh@h,harsh verma,Kavya Singh,Meera Nair,Adity@ Iy3r,Priya Gupta,Sn3h@ M@lhotr@
age,NaN,13,NaN,27,150,25,150,17,23,24,23,24,14,22,16,17,30,23 years,14,18
age_group,Young Adult (18-24),Young Adult (18-24),NaN,Young Adult (18-24),Young Adult (18-24),Young Adult (18-24),Young Adult (18-24),Young Adult (18-24),Adult (25-30),Young Adult (18-24),NaN,UNKNOWN,Young Adult (18-24),Adult (25-30),Teen (13-17),Adult (25-30),Teen (13-17),Young Adult (18-24),Adult (25-30),Adult (25-30)
city,Kolkata,Mumbai,Pune,Chennai,Bangalore,Mumbai,Hyderabad,Lucknow,Jaipur,Bangalore,Jaipur,Lucknow,Bangalore,PUNE,Chennai,Lucknow,Hyderabad,Lucknow,Delhi,Ahmedabad
email,simran.das@gmail.com,NaN,shreya.chopra@gmail.com,NaN,pooja.joshi@gmail.com,siddharth.das@gmail.com,priya.das@@gmail.com,zara.chopra@gmail.com,sneha.singh@gmail.com,NaN,priya.sharma@gmail.com,rohan.verma@gmail.com,simran.kumar@gmail.com,sneha.shah@gmail.com,harsh.verma@gmail.com,kavya.singh@gmail,meera.nairgmail.com,aditya.iyer@gmail.com,priya.gupta@@gmail.com,sneha.malhotragmail.com
phone,NaN,9025371511,9779267699,9966018593,971833,9685329623,9066815814,9903006244,99582-83857,9838348029,9672393684,9460116884,9653138725,9049190476,91391-57380,966604,9061928889,9128174403,9351682668,9651835622
manga_title,DR. STONE,One Punch Man,DEMON SLAYER,Death Note,The Promised Neverland,One Punch Man,One Punch Man,Black Clover,Mob Psycho 100,Chainsaw Man,Hunter x Hunter,Attack on Titan,Attack on Titan,Sword Art Online,One Piece,Demon Slayer,One Punch Man,Mob Psycho 100,Death Note,One Piece
volume_no,23.0,3.0,17.0,14.0,16.0,35.0,38.0,1.0,10.0,2.0,29.0,22.0,12.0,39.0,36.0,20.0,6.0,13.0,35.0,1.0
genre,Thriller,Shonen,Fantasy,ACTION,Seinen,Shonen,Slice of Life,ACTION,Horror,Shonen,shojo,Slice of Life,Action,Fantasy,Thriller,Romance,Seinen,Fantasy,Shojo,thriller
format,Paperback,Box Set,Box Set,Digital,Hardcover,Paperback,Digital,Hardcover,Box Set,Digital,Paperback,Paperback,Box Set,Limited Edition,Hardcover,Limited Edition,Limited Edition,NaN,Hardcover,Box Set
platform,Amazon,Amazon,MangaPlus Shop,-,Flipkart,Amazon,Book Depository,Crunchyroll Store,Crunchyroll Store,MangaPlus Shop,Amazon,Flipkart,Viz Media,Viz Media,NaN,Viz Media,Viz Media,Book Depository,NaN,Crunchyroll Store
payment_method,NaN,NaN,Cash,Cash,Debit Card,UPI,Net Banking,Debit Card,UPI,UPI,NaN,Credit Card,UPI,Wallet,Net Banking,NaN,Credit Card,NaN,Credit Card,Debit Card
unit_price,349,299.00,Rs.1299,799,349,1499/-,199,199,349,499,199,799.00,₹ 199,199,199.00,199,799,199,999,349
quantity,1.0,4.0,1.0,2.0,5.0,NaN,3.0,1.0,3.0,5.0,3.0,1.0,2.0,3.0,9999.0,3.0,3.0,3.0,4.0,5.0
total_amount,349,1196,1299,1598,1745,NaN,597,199,1047,NaN,597,799,398/-,597,NaN,597,2397,₹ 597,₹ 3996,1745
customer_rating,4.4,2.5,4.1,4.9,4.7,4.2,3.6,3.0,NaN,2.7,3.9,3.1,9.175353,3.0,3.1,5.0,4.1,2.9,2.9,4.2
purchase_date,06/08/22,19 February 2020,2021/07/06,27 September 2021,11/24/24,03-03-2022,August 2022,2022-05-12T00:00:00Z,15-01-2024,18 August 2020,2022/10/21,August 2024,01 January 2024,04.06.2023,22.05.2023,08 December 2020,01/16/22,March 2021,18.06.2020,2022/01/09
delivery_days,12.0,8.0,7.0,6.0,4.0,11.0,-1.0,1.0,NaN,1.0,2.0,1.0,9.0,2.0,11.0,15.0,10.0,5.0,6.0,9999.0
is_returned,False,1,True,yes,no,No,no,NaN,No,False,Yes,1,-,1,0,No,True,False,True,False
membership_tier,Bronze,NaN,NaN,Silver,NaN,Bronze,Platinum,NaN,Gold,Bronze,Bronze,Bronze,Platinum,Silver,Gold,Silver,Platinum,Silver,Platinum,NaN
discount_percent,25,0,0,20,5,15,NaN,20,0,20,25,25,20,15,5,0,10,10,20,10
coupon_used,No,Yes,none,Yes,NaN,Yes,-,Yes,none,No,NaN,none,NaN,No,NaN,No,NaN,No,Yes,none