# **Import Libraries**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print("Libraies Loaded Boss✅")

Libraies Loaded Boss✅

# **Data Exploration**

## *Load The Data*

In [3]:
File_path = input("Enter The File Path: ").replace('\\','\\')

df = pd.read_csv(File_path)
print('Data Loaded Successfully✅')

Data Loaded Successfully✅

## *Data Exploration*

In [4]:
# Data have 50k entry with 24 coloums
df.shape

(50000, 24)

In [5]:
# Transpose the data for better reading
df.head(10).T

,0,1,2,3,4,5,6,7,8,9
transaction_id,4784,28779,37597,44058,49115,10408,2620,3378,13924,29946
customer_id,CUST8189,CUST6564,CUST2413,CUST8973,CUST4060,CUST4547,CUST2407,CUST5476,CUST5131,CUST1117
customer_name,SIMRAN DAS,Nikhil Reddy,Shreya Chopra,Arjun Joshi,Pooja Joshi,Siddharth Das,Priya Das,Zara Chopra,sneha singh,Riya Iyer
age,NaN,13,NaN,27,150,25,150,17,23,24
age_group,Young Adult (18-24),Young Adult (18-24),NaN,Young Adult (18-24),Young Adult (18-24),Young Adult (18-24),Young Adult (18-24),Young Adult (18-24),Adult (25-30),Young Adult (18-24)
city,Kolkata,Mumbai,Pune,Chennai,Bangalore,Mumbai,Hyderabad,Lucknow,Jaipur,Bangalore
email,simran.das@gmail.com,NaN,shreya.chopra@gmail.com,NaN,pooja.joshi@gmail.com,siddharth.das@gmail.com,priya.das@@gmail.com,zara.chopra@gmail.com,sneha.singh@gmail.com,NaN
phone,NaN,9025371511,9779267699,9966018593,971833,9685329623,9066815814,9903006244,99582-83857,9838348029
manga_title,DR. STONE,One Punch Man,DEMON SLAYER,Death Note,The Promised Neverland,One Punch Man,One Punch Man,Black Clover,Mob Psycho 100,Chainsaw Man
volume_no,23.0,3.0,17.0,14.0,16.0,35.0,38.0,1.0,10.0,2.0
genre,Thriller,Shonen,Fantasy,ACTION,Seinen,Shonen,Slice of Life,ACTION,Horror,Shonen
format,Paperback,Box Set,Box Set,Digital,Hardcover,Paperback,Digital,Hardcover,Box Set,Digital
platform,Amazon,Amazon,MangaPlus Shop,-,Flipkart,Amazon,Book Depository,Crunchyroll Store,Crunchyroll Store,MangaPlus Shop
payment_method,NaN,NaN,Cash,Cash,Debit Card,UPI,Net Banking,Debit Card,UPI,UPI
unit_price,349,299.00,Rs.1299,799,349,1499/-,199,199,349,499
quantity,1.0,4.0,1.0,2.0,5.0,NaN,3.0,1.0,3.0,5.0
total_amount,349,1196,1299,1598,1745,NaN,597,199,1047,NaN
customer_rating,4.4,2.5,4.1,4.9,4.7,4.2,3.6,3.0,NaN,2.7
purchase_date,06/08/22,19 February 2020,2021/07/06,27 September 2021,11/24/24,03-03-2022,August 2022,2022-05-12T00:00:00Z,15-01-2024,18 August 2020
delivery_days,12.0,8.0,7.0,6.0,4.0,11.0,-1.0,1.0,NaN,1.0
is_returned,False,1,True,yes,no,No,no,NaN,No,False
membership_tier,Bronze,NaN,NaN,Silver,NaN,Bronze,Platinum,NaN,Gold,Bronze
discount_percent,25,0,0,20,5,15,NaN,20,0,20
coupon_used,No,Yes,none,Yes,NaN,Yes,-,Yes,none,No

In [6]:
df.tail(10).T

,49990,49991,49992,49993,49994,49995,49996,49997,49998,49999
transaction_id,13278,6571,37752,5877,40272,11641,19165,35949,42242,7566
customer_id,CUST7482,CUST7829,CUST4657,CUST8558,CUST1143,CUST9704,CUST8459,CUST4192,CUST1189,CUST8347
customer_name,Divya Patel,Harsh Joshi,Shreya Shah,Karan Malhotra,Harsh Shah,Pooja Verma,Vikram Das,Amit Gupta,AMIT SINGH,Nikhil Reddy
age,30,27,-27,18,20,24,17,30,28,30
age_group,Young Adult (18-24),Young Adult (18-24),Adult (25-30),Young Adult (18-24),Teen (13-17),Adult (25-30),Teen (13-17),Adult (25-30),Adult (25-30),Young Adult (18-24)
city,Kolkata,Pune,Kolkata,Bangalore,Ahmedabad,Lucknow,Mumbai,Mumbai,Delhi,Pune
email,divya.patel@gmail.com,harsh.joshi@gmail.com,shreya.shah@gmail.com,karan.malhotra@gmail.com,harsh.shah@gmail.com,pooja.vermagmail.com,vikram.das@gmail.com,amit.gupta@gmail.com,amit.singh@gmail,nikhil.reddy@gmail.com
phone,92811-73105,9727005035,9005758089,NaN,9876829355,NaN,9709716982,9678982355,9831289524,9605167734
manga_title,Spy x Family,Dr. Stone,Attack on Titan,One Piece,Naruto,Fairy Tail,Fullmetal Alchemist,Vinland Saga,Fairy Tail,BLEACH
volume_no,NaN,21.0,-37.0,NaN,36.0,34.0,13.0,9.0,13.0,NaN
genre,Slice of Life,Isekai,Fantasy,Shonen,Fantasy,Slice of Life,Shojo,Romance,Thriller,ROMANCE
format,Limited Edition,Paperback,Limited Edition,NaN,Limited Edition,Digital,Hardcover,Digital,Hardcover,Box Set
platform,Crunchyroll Store,Local Store,Flipkart,Flipkart,Crunchyroll Store,Flipkart,Book Depository,Book Depository,MangaPlus Shop,Amazon
payment_method,Net Banking,Debit Card,UPI,Debit Card,Credit Card,Cash,UPI,Wallet,Credit Card,Cash
unit_price,599,299,599,NaN,199,349,599,349,1299,349
quantity,4.0,3.0,3.0,2.0,4.0,1.0,5.0,4.0,NaN,1.0
total_amount,999999,897/-,1797,998,796,349,2995,NaN,5196,349
customer_rating,2.8,3.1,4.0,7.360084,3.6,4.9,4.1,2.7,-1.0,3.2
purchase_date,June 2024,19.03.2023,2023/05/22,2020/11/19,11.12.2021,20-08-2023,December 2022,22-12-2020,October 2024,24.08.2020
delivery_days,3.0,12.0,5.0,10.0,11.0,3.0,2.0,3.0,-3.0,9.0
is_returned,0,yes,yes,no,NO,True,NaN,0,No,No
membership_tier,bronze,SILVER,Gold,Gold,UNKNOWN,Platinum,Gold,Silver,Gold,Platinum
discount_percent,0,20,25,NaN,5,5,5,5,10,20
coupon_used,Unknown,NaN,NaN,Unknown,none,NaN,none,Yes,NaN,No

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    50000 non-null  int64
 1   customer_id       49007 non-null  str
 2   customer_name     50000 non-null  str
 3   age               47504 non-null  str
 4   age_group         47992 non-null  str
 5   city              50000 non-null  str
 6   email             46987 non-null  str
 7   phone             47508 non-null  str
 8   manga_title       50000 non-null  str
 9   volume_no         47557 non-null  float64
 10  genre             50000 non-null  str
 11  format            48068 non-null  str
 12  platform          48018 non-null  str
 13  payment_method    48030 non-null  str
 14  unit_price        47472 non-null  str
 15  quantity          47417 non-null  float64
 16  total_amount      47396 non-null  str
 17  customer_rating   45933 non-null  float64
 18  purchase_date     45050 non-null  str
 19  delivery_days     47483 non-null  float64
 20  is_returned       47921 non-null  str
 21  membership_tier   41437 non-null  str
 22  discount_percent  48055 non-null  str
 23  coupon_used       29723 non-null  str
dtypes: float64(4), int64(1), str(19)
memory usage: 9.2 MB

In [8]:
#Drop the 50%> NaN values col (Optional)
print('NaN Value % in col: ')
print(round((df.isna().sum()/df.count())*100,2))

NaN Value % in col:
transaction_id       0.00
customer_id          2.03
customer_name        0.00
age                  5.25
age_group            4.18
city                 0.00
email                6.41
phone                5.25
manga_title          0.00
volume_no            5.14
genre                0.00
format               4.02
platform             4.13
payment_method       4.10
unit_price           5.33
quantity             5.45
total_amount         5.49
customer_rating      8.85
purchase_date       10.99
delivery_days        5.30
is_returned          4.34
membership_tier     20.67
discount_percent     4.05
coupon_used         68.22
dtype: float64

In [9]:
print("Duplicates in the Data is",df.duplicated().sum())

Duplicates in the Data is 943

# **Data Cleaning**

In [153]:
df_copy = df.copy()
print('Copy created')

Copy created

## *Data Type Correction and Neccesory steps*

In [ ]:
# Customer name column
replacements = {'@':'a','3':'e','0':'o'}

df_copy['customer_name'] = (
    df_copy['customer_name']
    .replace(replacements, regex=True)
    .str.strip()
    .str.title())



# Age Column
replacements = {'years':'','unknown':np.nan}
for char, replacement in replacements.items():
    df_copy['age'] = df_copy['age'].replace(char,replacement,regex=True).str.strip()
df_copy['age'] = df_copy['age'].astype('float')



#Age group
unknown = df_copy['age_group'].unique().tolist()
valid = ['Young Adult (18-24)','Adult (25-30)','Teen (13-17)']
to_replace = {item: 'Unknown' for item in unknown if item not in valid}
df_copy['age_group'] = df_copy['age_group'].replace(to_replace)
df_copy = df_copy[df_copy['age_group'] != '-']



# City Column
df_copy['city'] = df_copy['city'].str.strip().str.title()
replacements = {'Dlhi':'Delhi','Chenna':'Chennai','Bangalroe':'Bangalore'}
for char,replacement in replacements.items():
    df_copy['city'] = df_copy['city'].replace(char,replacement)
    
    

# Email Column
df_copy['email'] = df_copy['email'].replace('@@','@',regex=True)
df_copy['email'] = df_copy['email'].str.strip()


# Phone Column
df_copy['phone'] = df_copy['phone'].str.replace(r'\+91|-|\s', '', regex=True)
df_copy.loc[(df_copy['phone'].str.len() != 10),'phone'] = 'Unknown'



# Manga title Column
df_copy['manga_title'] = (
    df_copy['manga_title']
    .str.strip()
    .str.lower()
)

df_copy['manga_title'] = (
    df_copy['manga_title']
    .str.replace(r'0', 'o', regex=True)
    .str.replace(r'@', 'a', regex=True)
    .str.replace(r'3', 'e', regex=True)
)


mapping = {
    'narut': 'naruto',
    'narutoo': 'naruto',
    'narut0': 'naruto',

    'one piec': 'one piece',
    'one piecee': 'one piece',

    'attack on tita': 'attack on titan',
    'attack on titann': 'attack on titan',

    'demon slaye': 'demon slayer',
    'dem0n slayer': 'demon slayer',

    'tokyo ghou': 'tokyo ghoul',
    't0kyo gh0ul': 'tokyo ghoul',

    'black clove': 'black clover',
    'black cl0ver': 'black clover',

    'chainsaw ma': 'chainsaw man',

    'mob psycho 1o': 'mob psycho 100',
    'mob psycho 10': 'mob psycho 100',
    'm0b psych0 100': 'mob psycho 100',

    'dr. ston': 'dr. stone',
    'dr. st0ne': 'dr. stone',

    'fullmetal alchemis': 'fullmetal alchemist',

    'death not': 'death note',
    'death n0te': 'death note',

    'jujutsu kaise': 'jujutsu kaisen',

    'vinland sag': 'vinland saga',

    'fairy tai': 'fairy tail',

    'bleac': 'bleach',

    'hunter x hunte': 'hunter x hunter',

    'my hero academi': 'my hero academia',
    'my her0 academia': 'my hero academia',

    'sword art onlin': 'sword art online',
    'sw0rd art online': 'sword art online',

    'the promised neverlan': 'the promised neverland',
    'the pr0mised neverland': 'the promised neverland',

    'berser': 'berserk',

    'haikyuu': 'haikyu',
    'haikyuu ': 'haikyu',

    "jojo's bizarre adventur": "jojo's bizarre adventure",
    "j0j0's bizarre adventure": "jojo's bizarre adventure"
}

df_copy['manga_title'] = df_copy['manga_title'].replace(mapping)

df_copy['manga_title'] = df_copy['manga_title'].str.title()

final_fix = {
    'Mob Psycho 1Oo': 'Mob Psycho 100',
    'One Punch Ma': 'One Punch Man',
    'Spy X Famil': 'Spy X Family',
    'Dragon Ball': 'Dragon Ball Z'
}

df_copy['manga_title'] = df_copy['manga_title'].replace(final_fix)

df_copy['manga_title'] = df_copy['manga_title'].str.replace(r"'S", "'s", regex=True)

df_copy['manga_title'] = df_copy['manga_title'].str.strip()



# Volume Column
df_copy.loc[df_copy['volume_no'] > 100, 'volume_no'] = np.nan
df_copy.loc[df_copy['volume_no'] < 0, 'volume_no'] = np.nan




# Genre Column
df_copy['genre'] = df_copy['genre'].str.strip().str.title()
replacements = {'Acton':'Action','Isekkai':'Isekai'}
for char,replacement in replacements.items():
    df_copy['genre'] = df_copy['genre'].replace(char,replacement)
    
    
# Payment, Platform, Format Column
columns = ['payment_method','platform','format']
for items in columns:
    df_copy[items] = (
        df_copy[items]
        .str.strip()
        .str.title()
        .replace(['-','None','Na'], 'Unknown')
        .fillna('Unknown')
)
    
    
    
# Price Column
df_copy['unit_price'] = df_copy['unit_price'].replace(['Rs.','/-','₹ '],'',regex=True).astype('float')
df_copy.loc[df_copy['unit_price'] > 1599, 'unit_price'] = np.nan
df_copy.loc[df_copy['unit_price'] <= 0, 'unit_price'] = np.nan
df_copy['unit_price'] = df_copy['unit_price'].fillna(round(df_copy['unit_price'].median(),2))



# Quantity Column
df_copy.loc[df_copy['quantity'] > 10, 'quantity'] = np.nan
df_copy.loc[df_copy['quantity'] <= 0, 'quantity'] = np.nan
df_copy['quantity'] = df_copy['quantity'].fillna(round(df_copy['quantity'].median(),0))



# Total Amount Column
df_copy['total_amount'] = df_copy['total_amount'].replace(['Rs.','/-','₹ '],'',regex=True).astype('float')
df_copy['total_amount'] = (df_copy['unit_price'])*(df_copy['quantity'])




# Rating Column
df_copy['customer_rating'] = df_copy['customer_rating'].round(2)
df_copy.loc[df_copy['customer_rating']<0,'customer_rating'] = np.nan
df_copy.loc[df_copy['customer_rating']>10,'customer_rating'] = np.nan
df_copy['customer_rating'] = df_copy['customer_rating'].fillna(round(df_copy['customer_rating'].median(),2))




# Date Column
df_copy['purchase_date'] = df_copy['purchase_date'].dt.strftime('%d-%m-%y')
df_copy['purchase_date'] = pd.to_datetime(df_copy['purchase_date'], errors='coerce',utc=True)



# Delivery Time Column
df_copy.loc[df_copy['delivery_days'] > 10, 'delivery_days'] = np.nan
df_copy.loc[df_copy['delivery_days'] <= 0, 'delivery_days'] = np.nan
df_copy['delivery_days'] = df_copy['delivery_days'].fillna(round(df_copy['delivery_days'].median(),0))



# Returend Column
df_copy['is_returned'] = df_copy['is_returned'].str.strip().str.title().replace(['False','Na','0'],'No')
df_copy['is_returned'] = df_copy['is_returned'].str.strip().str.title().replace(['1','True'],'Yes')
df_copy['is_returned'] = df_copy['is_returned'].str.strip().str.title().replace(['-','None'],'Unknown')
df_copy['is_returned'] = df_copy['is_returned'].fillna('Unknown')

In [167]:
df_copy['is_returned'].unique().tolist()

['No', 'Yes', 'Unknown']

In [159]:
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    50000 non-null  int64
 1   customer_id       49007 non-null  str
 2   customer_name     50000 non-null  str
 3   age               46471 non-null  float64
 4   age_group         50000 non-null  str
 5   city              50000 non-null  str
 6   email             46987 non-null  str
 7   phone             50000 non-null  str
 8   manga_title       50000 non-null  str
 9   volume_no         43538 non-null  float64
 10  genre             50000 non-null  str
 11  format            50000 non-null  str
 12  platform          50000 non-null  str
 13  payment_method    50000 non-null  str
 14  unit_price        50000 non-null  float64
 15  quantity          50000 non-null  float64
 16  total_amount      50000 non-null  float64
 17  customer_rating   50000 non-null  float64
 18  purchase_date     45050 non-null  str
 19  delivery_days     47483 non-null  float64
 20  is_returned       47921 non-null  str
 21  membership_tier   41437 non-null  str
 22  discount_percent  48055 non-null  str
 23  coupon_used       29723 non-null  str
dtypes: float64(7), int64(1), str(16)
memory usage: 9.2 MB